### ISSUE TITLE
How did you Ingredient detection?

### ISSUE THREAD

**Issue by tomoki-oke** [torralba-lab/im2recipe#24] opened 2019-01-20 08:23 UTC
Hello.
In the paper where this model was proposed, ingredients were detected through an LSTM model.
I want to know how did you train the LSTM model, or what model you chose.

**Comment by nhynes** [comment] 2019-01-20 09:46
A few of the data sources had (somewhat roughly) included ingredient annotations. These weren't released as part of the full dataset because they were too inconsistently present.

The model is dead simple: roll up the words using an LSTM and classify the ingredient as one of the top N (where N = O(100), IIRC).

If you want to train your own, you might have good luck with a recipe site that follows the `Recipe` schema or applies some special markup to their ingredients.

**Closed by nhynes** 2019-01-20 09:46 UTC

**Comment by devanshbatra04** [comment] 2019-05-29 17:19
Hi, 
I am trying to reproduce this approach for a similar dataset.

I am really sorry but I don't understand what's meant by rolling up the words using the LSTM. What was the input like? I am guessing there was an embedding layer too. 

The paper mentioned the bi-directional lstm that classifies the ingredients text word by word. But that wasn't too clear. :/

Would really appreciate any help at all. Thanks!
